#!/usr/bin/env python

import sys
sys.path.append('../../../plugins')

from __mplugin import MPlugin
from __mplugin import OK, WARNING, CRITICAL, UNKNOWN, TIMEOUT

import urllib
import socket
import json
import requests
from time import time

class CheckURL(MPlugin):
    def run(self):
        url = self.config.get('url')
        method = self.config.get('method')
        headers_raw = self.config.get('headers')
        data_raw = self.config.get('data')
        content = ''
        if not url:
           self.exit(CRITICAL, message="Invalid URL")

        headers = {}

        if headers_raw:
            headers_list = headers_raw.split(',')
            for item in headers_list:
                key, value = item.split(':')
                headers[key.strip()] = value.strip()

        data = {}

        if data_raw:
            data_list = data_raw.split(',')
            for item in data_list:
                key, value = item.split(':')
                data[key.strip()] = value.strip()

        # Set timeout
        timeout = self.config.get('timeout',TIMEOUT)
        socket.setdefaulttimeout(int(timeout))

        if method == 'GET':
            start_time = time()
            # Fetch
            try:
                urlopen = urllib.urlopen(url)
            except:
                self.exit(CRITICAL, message="Unable to open URL")

            end_time = time()
            mytime = "%.2f" %(end_time - start_time)

            # Get size
            size = 0
            headers = urlopen.info()
            content = ''.join(urlopen.readlines())
            code = urlopen.getcode()

            if "content-length" in headers:
                size = int(headers["Content-Length"])
            else:
                size = len(content)
            urlopen.close()

        elif method == 'POST':
            start_time = time()

            try:
                r = requests.post(url, data=json.dumps(data), headers = headers)
            except:
                self.exit(CRITICAL, message="Unable to POST to open URL")

            if not r.ok:
                self.exit(CRITICAL, message="POST returned with error with status code "+str(r.status_code))

            end_time = time()
            mytime = "%.2f" %(end_time - start_time)

            # Get size
            size = 0

            content = r.content
            code = r.status_code
            size = len(content)

        data = {
            'content': content,
            'code': code,
            'size': size,
            'time': mytime
        }

        metrics = {
            'Content Size': {
              'size': size
            },
            'Response time': {
              'time': mytime
            }
        }

        self.exit(OK,data,metrics)


monitor = CheckURL()
monitor.run()