#!/usr/bin/env python

import sys
sys.path.append('../../../plugins')

from __mplugin import MPlugin
from __mplugin import OK, WARNING, CRITICAL, UNKNOWN, TIMEOUT

import urllib
import socket

class CheckURL(MPlugin):
    def run(self):
        url = self.config.get('url')
        content = ''
        if not url:
           self.exit(CRITICAL, message="Invalid URL")
        
        # Set timeout
        socket.setdefaulttimeout(self.config.get('timeout',TIMEOUT))
        
        # Fetch
        try:
            urlopen = urllib.urlopen(url)
        except:
            self.exit(CRITICAL, message="Unable to open URL")
        
        # Get size
        size = 0
        headers = urlopen.info()
        if "content-length" in headers:
            size = int(headers["Content-Length"])
        
        data = {
            'content': ''.join(urlopen.readlines()),
            'code': urlopen.getcode(),
            'size': size
        }
        
        metrics = {
            'Content Size': {
              'size': size
            }
        }
        
        urlopen.close()
        self.exit(OK,data,metrics)
        

monitor = CheckURL()
monitor.run()
